# Spotify解锁
# 2026/4/15
# 去广告采用的Amlabort的，去随机播放采用的app2smile的

hostname = spclient.wg.spotify.com, *.spclient.spotify.com

# 1) Header
^https:\/\/(spclient\.wg\.spotify\.com|.*-spclient\.spotify\.com(:443)?)\/user-customization-service\/v1\/customize$ url script-request-header https://raw.githubusercontent.com/LiamChau/rewrite/main/spotify-shuffle-fix.js

# 2) Ads
^https:\/\/(?:\w+-spclient|spclient\.wg)\.spotify\.com\/pendragon\/ url reject-dict
^https:\/\/.*-spclient\.spotify\.com\/capping-api\/ url reject-dict
^https:\/\/.*-spclient\.spotify\.com\/partner- url reject-dict
^https:\/\/.*-spclient\.spotify\.com\/pam-view-service\/ url reject-dict
^https:\/\/.*-spclient\.spotify\.com\/social-connect\/v.\/sessions\/ url reject-dict

# 3) gabo
^https:\/\/(.*-spclient\.spotify\.com|spclient\.wg\.spotify\.com)\/gabo-receiver-service url script-request-body https://raw.githubusercontent.com/Amlabort/MY_clash/main/files/lpx/js/spot-gabo.js

# 4) artist / album
^https:\/\/(spclient\.wg\.spotify\.com|.*-spclient\.spotify\.com)\/(artistview\/v1\/artist|album-entity-view\/v2\/album)\/ url script-request-body https://raw.githubusercontent.com/Amlabort/MY_clash/main/files/lpx/js/spot-Json-copy.js

# 5) Premium proto
^https:\/\/(spclient\.wg\.spotify\.com|.*-spclient\.spotify\.com)\/(bootstrap\/v1\/bootstrap|user-customization-service\/v1\/customize)(\?.*)?$ url script-response-body https://raw.githubusercontent.com/Amlabort/MY_clash/main/files/lpx/js/spot-proto-eevee.js

# 6) Restriction cleaner
^https:\/\/(spclient\.wg\.spotify\.com|.*-spclient\.spotify\.com)\/(bootstrap\/v1\/bootstrap|user-customization-service\/v1\/customize)(\?.*)?$ url script-response-body https://raw.githubusercontent.com/LiamChau/rewrite/main/spotify-restriction-cleaner.js